### ISSUE TITLE
No HTTP resource was found that matches the request URI 'http://passwordutility.net/api/password/validate'.

### ISSUE THREAD

**Issue by richin13** [cmatskas/PasswordUtility#1]
I am not being able to use the API from a PHP script nor cURL command line tool. In both I received the following message:
string(214) "{"Message":"No HTTP resource was found that matches the request URI 'https://passwordutility.net/api/password/validate'.","MessageDetail":"No action was found on the controller 'Password' that matches the request."}"

**Comment by cmatskas** [comment]
Thanks Ricardo.

I'll have a look later on today.

CM

On Sat, Oct 24, 2015 at 11:10 PM -0700, "Ricardo" notifications@github.com wrote:

I am not being able to use the API from a PHP script nor cURL command line tool. In both I received the following message:

string(214) "{"Message":"No HTTP resource was found that matches the request URI 'https://passwordutility.net/api/password/validate'.","MessageDetail":"No action was found on the controller 'Password' that matches the request."}"

**Comment by cmatskas** [comment]
@richin13 I'm unable to recreate this. I can use both the Swagger API and a standalone rest client and this works fine for me:

https://passwordutility.net/api/password/validate?password=123456789
Please note that this operation is a POST and not a GET.
Could you please test again and let me know if the issue persists? Thanks for your feedback

**Comment by richin13** [comment]
Hi I tried again with cURL and it worked. Thank you

**Comment by cmatskas** [comment]
Thanks for letting me know :)

Sent from Outlook

On Wed, Nov 11, 2015 at 9:52 AM -0800, "Ricardo" notifications@github.com wrote:

Hi I tried again with cURL and is working. Thank you
